# Generated by Django 4.1.5 on 2023-10-27 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diskusiBook', '0002_post_date_reply_comment_post_comment'),
    ]

    operations = [
    ]
