# Generated by Django 4.2.6 on 2023-10-29 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diskusiBook', '0005_alter_comment_post_alter_post_book_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Book',
            new_name='book',
        ),
        migrations.AlterField(
            model_name='reply',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='diskusiBook.comment'),
        ),
    ]
