# Generated by Django 4.2.6 on 2023-10-28 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diskusiBook', '0005_alter_comment_post_alter_post_book_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Book',
            new_name='book_id',
        ),
    ]
