# Generated by Django 4.2.6 on 2023-10-28 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diskusiBook', '0006_rename_book_post_book_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='book_id',
            new_name='book',
        ),
    ]
