# Generated by Django 4.2.6 on 2023-10-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_book_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='display_title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
