# Generated by Django 4.2.6 on 2023-10-29 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_book_description_book_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
