# Generated by Django 4.2.6 on 2023-10-29 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_delete_searchhistory'),
        ('main', '0008_book_genre'),
    ]

    operations = [
    ]
