# Generated by Django 4.2.6 on 2023-10-29 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0009_merge_0007_delete_searchhistory_0008_book_genre"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyMainBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("display_title", models.CharField(max_length=255)),
                ("authors", models.TextField()),
                ("image", models.TextField()),
                ("description", models.TextField()),
                ("isbn", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
